import { AsyncLocalStorage } from "node:async_hooks";

import { betterAuth } from "better-auth";
import { APIError, createAuthMiddleware } from "better-auth/api";
import { nextCookies } from "better-auth/next-js";
import { username } from "better-auth/plugins";
import bcrypt from "bcryptjs";
import { headers } from "next/headers";

import { pool } from "./db";

// Self-hosted auth (docs/decisions/auth-self-hosted.md): Better Auth with
// database sessions and username + password sign-in. Its tables live in
// migrations/0018_better_auth: the `user` model maps onto the existing users
// table (every users(id) foreign key stays), the rest onto sessions,
// accounts and verifications, all with snake_case columns and uuid ids
// generated by Postgres.

// Accounts (docs/MEMBERS.md): sign-up is only for bootstrapping. The first
// user to sign up on a fresh install becomes the admin; after that the
// public sign-up is closed and only an admin creates accounts, from
// Settings > Members (app/dashboard/settings/members/actions.ts), which runs
// Better Auth's sign-up inside asAdminAccountCreation. Both checks below
// (the endpoint hook and the user-create database hook) enforce that on the
// server, whatever the UI shows; the database hook also covers any other
// path that would create a user.
const accountCreation = new AsyncLocalStorage<"admin">();

export function asAdminAccountCreation<T>(fn: () => Promise<T>): Promise<T> {
  return accountCreation.run("admin", fn);
}

export async function installHasUsers(): Promise<boolean> {
  const { rows } = await pool.query<{ any: boolean }>(`SELECT EXISTS (SELECT 1 FROM users) AS any`);
  return rows[0].any;
}

const signUpClosed = () =>
  new APIError("FORBIDDEN", {
    code: "SIGN_UP_CLOSED",
    message: "Sign-up is closed. Ask an administrator to create your account.",
  });

async function assertCanCreateUser() {
  if (accountCreation.getStore() !== "admin" && (await installHasUsers())) throw signUpClosed();
}

// Extra origins allowed to call the auth endpoints besides BETTER_AUTH_URL,
// comma-separated (e.g. a second domain in front of the same app).
const extraOrigins = (process.env.BETTER_AUTH_TRUSTED_ORIGINS ?? "")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);

export const authServer = betterAuth({
  secret: process.env.BETTER_AUTH_SECRET,
  baseURL: process.env.BETTER_AUTH_URL,
  trustedOrigins: extraOrigins,
  database: pool,
  advanced: {
    database: { generateId: "uuid" },
  },
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    // Off so an admin creating an account isn't signed in as it; the
    // bootstrap sign-up (app/signup/actions.ts) signs in explicitly.
    autoSignIn: false,
    // Passwords from before Better Auth are bcrypt (cost 12), moved into
    // accounts.password by the migration; keep bcrypt for new ones too so
    // there is a single hash format.
    password: {
      hash: (password) => bcrypt.hash(password, 12),
      verify: ({ hash, password }) => bcrypt.compare(password, hash),
    },
  },
  user: {
    modelName: "users",
    fields: {
      emailVerified: "email_verified",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  session: {
    modelName: "sessions",
    fields: {
      userId: "user_id",
      expiresAt: "expires_at",
      ipAddress: "ip_address",
      userAgent: "user_agent",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  account: {
    modelName: "accounts",
    fields: {
      userId: "user_id",
      accountId: "account_id",
      providerId: "provider_id",
      accessToken: "access_token",
      refreshToken: "refresh_token",
      idToken: "id_token",
      accessTokenExpiresAt: "access_token_expires_at",
      refreshTokenExpiresAt: "refresh_token_expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  verification: {
    modelName: "verifications",
    fields: {
      expiresAt: "expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  hooks: {
    before: createAuthMiddleware(async (ctx) => {
      if (ctx.path === "/sign-up/email") await assertCanCreateUser();
    }),
  },
  databaseHooks: {
    user: {
      create: {
        before: async () => {
          await assertCanCreateUser();
        },
        // The oldest user is the bootstrap admin. Two sign-ups racing on a
        // fresh install can both pass the check above; only the first
        // becomes admin, the other stays a member.
        after: async (user) => {
          await pool.query(
            `UPDATE users SET role = 'admin'
              WHERE id = $1 AND id = (SELECT id FROM users ORDER BY created_at, id LIMIT 1)`,
            [user.id],
          );
        },
      },
    },
    session: {
      create: {
        // A disabled account can't sign in (its sessions were deleted when
        // it was disabled).
        before: async (session) => {
          const { rows } = await pool.query<{ disabled: boolean }>(
            `SELECT disabled_at IS NOT NULL AS disabled FROM users WHERE id = $1`,
            [session.userId],
          );
          if (rows[0]?.disabled) {
            throw new APIError("FORBIDDEN", {
              code: "ACCOUNT_DISABLED",
              message: "This account is disabled.",
            });
          }
        },
      },
    },
  },
  plugins: [
    username({
      schema: {
        user: { fields: { displayUsername: "display_username" } },
      },
    }),
    // Must stay last: it sets cookies from server actions (sign-in, sign-up).
    nextCookies(),
  ],
});

// The current session ({ user, session }) or null, for server components,
// server actions and route handlers: `(await auth())?.user.id`.
export async function auth() {
  return authServer.api.getSession({ headers: await headers() });
}
