import { betterAuth } from "better-auth";
import { nextCookies } from "better-auth/next-js";
import { username } from "better-auth/plugins";
import bcrypt from "bcryptjs";
import { headers } from "next/headers";

import { pool } from "./db";

// Self-hosted auth (docs/decisions/auth-self-hosted.md): Better Auth with
// database sessions and username + password sign-in. Its tables live in
// migrations/0018_better_auth: the `user` model maps onto the existing users
// table (every users(id) foreign key stays), the rest onto sessions,
// accounts and verifications, all with snake_case columns and uuid ids
// generated by Postgres.

// Extra origins allowed to call the auth endpoints besides BETTER_AUTH_URL,
// comma-separated (e.g. a second domain in front of the same app).
const extraOrigins = (process.env.BETTER_AUTH_TRUSTED_ORIGINS ?? "")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);

export const authServer = betterAuth({
  secret: process.env.BETTER_AUTH_SECRET,
  baseURL: process.env.BETTER_AUTH_URL,
  trustedOrigins: extraOrigins,
  database: pool,
  advanced: {
    database: { generateId: "uuid" },
  },
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    // Passwords from before Better Auth are bcrypt (cost 12), moved into
    // accounts.password by the migration; keep bcrypt for new ones too so
    // there is a single hash format.
    password: {
      hash: (password) => bcrypt.hash(password, 12),
      verify: ({ hash, password }) => bcrypt.compare(password, hash),
    },
  },
  user: {
    modelName: "users",
    fields: {
      emailVerified: "email_verified",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  session: {
    modelName: "sessions",
    fields: {
      userId: "user_id",
      expiresAt: "expires_at",
      ipAddress: "ip_address",
      userAgent: "user_agent",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  account: {
    modelName: "accounts",
    fields: {
      userId: "user_id",
      accountId: "account_id",
      providerId: "provider_id",
      accessToken: "access_token",
      refreshToken: "refresh_token",
      idToken: "id_token",
      accessTokenExpiresAt: "access_token_expires_at",
      refreshTokenExpiresAt: "refresh_token_expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  verification: {
    modelName: "verifications",
    fields: {
      expiresAt: "expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  plugins: [
    username({
      schema: {
        user: { fields: { displayUsername: "display_username" } },
      },
    }),
    // Must stay last: it sets cookies from server actions (sign-in, sign-up).
    nextCookies(),
  ],
});

// The current session ({ user, session }) or null, for server components,
// server actions and route handlers: `(await auth())?.user.id`.
export async function auth() {
  return authServer.api.getSession({ headers: await headers() });
}
