import { AsyncLocalStorage } from "node:async_hooks";

import { cimd } from "@better-auth/cimd";
import { fetchClientMetadataResource } from "@better-auth/cimd/node";
import { mcp } from "@better-auth/mcp";
import { betterAuth } from "better-auth";
import { APIError, createAuthMiddleware } from "better-auth/api";
import { nextCookies } from "better-auth/next-js";
import { jwt, username } from "better-auth/plugins";
import bcrypt from "bcryptjs";
import { headers } from "next/headers";

import { pool } from "./db";

// Self-hosted auth (docs/decisions/auth-self-hosted.md): Better Auth with
// database sessions and username + password sign-in. Its tables live in
// server/migrations/0018_better_auth: the `user` model maps onto the existing users
// table (every users(id) foreign key stays), the rest onto sessions,
// accounts and verifications, all with snake_case columns and uuid ids
// generated by Postgres.

// Accounts (docs/MEMBERS.md): sign-up is only for bootstrapping. The first
// user to sign up on a fresh install becomes the admin; after that the
// public sign-up is closed and only an admin creates accounts, from
// Settings > Members (app/dashboard/settings/members/actions.ts), which runs
// Better Auth's sign-up inside asAdminAccountCreation. Both checks below
// (the endpoint hook and the user-create database hook) enforce that on the
// server, whatever the UI shows; the database hook also covers any other
// path that would create a user.
const accountCreation = new AsyncLocalStorage<"admin">();

export function asAdminAccountCreation<T>(fn: () => Promise<T>): Promise<T> {
  return accountCreation.run("admin", fn);
}

export async function installHasUsers(): Promise<boolean> {
  const { rows } = await pool.query<{ any: boolean }>(`SELECT EXISTS (SELECT 1 FROM users) AS any`);
  return rows[0].any;
}

const signUpClosed = () =>
  new APIError("FORBIDDEN", {
    code: "SIGN_UP_CLOSED",
    message: "Sign-up is closed. Ask an administrator to create your account.",
  });

async function assertCanCreateUser() {
  if (accountCreation.getStore() !== "admin" && (await installHasUsers())) throw signUpClosed();
}

// Extra origins allowed to call the auth endpoints besides BETTER_AUTH_URL,
// comma-separated (e.g. a second domain in front of the same app).
export const extraOrigins = (process.env.BETTER_AUTH_TRUSTED_ORIGINS ?? "")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);

// The dashboard's public URL (BETTER_AUTH_URL), without a trailing slash.
export function appBaseUrl(): string {
  return (process.env.BETTER_AUTH_URL ?? "http://localhost:3000").replace(/\/$/, "");
}

// MCP sign-in (docs/MCP.md#authentication, docs/decisions/mcp-auth.md):
// mcp() makes this app the OAuth 2.1 authorization server for /api/mcp,
// jwt() signs its access tokens, cimd() lets a client identify itself by a
// metadata document URL (Claude Code's is
// https://claude.ai/oauth/claude-code-client-metadata). Dynamic Client
// Registration stays off. The tables are server/migrations/0026_mcp, whose
// header lists this same model and field mapping; a field not listed keeps
// its name.
//
// Scopes: mcp:read is every tool today; offline_access lets Claude Code
// refresh instead of signing in every hour. mcp:write is reserved for the
// later write tools and is deliberately not offered, so it can't be granted.
export const MCP_SCOPES = ["mcp:read", "offline_access"] as const;

// The MCP server's resource identifier (RFC 8707): access tokens are
// audience-bound to it.
export function mcpResourceUrl(): string {
  return `${appBaseUrl()}/api/mcp`;
}

const jwtSchema = {
  jwks: {
    modelName: "jwks",
    fields: {
      publicKey: "public_key",
      privateKey: "private_key",
      createdAt: "created_at",
      expiresAt: "expires_at",
    },
  },
};

const oauthProviderSchema = {
  oauthClient: {
    modelName: "oauth_clients",
    fields: {
      clientId: "client_id",
      clientSecret: "client_secret",
      clientDiscoveryId: "client_discovery_id",
      skipConsent: "skip_consent",
      enableEndSession: "enable_end_session",
      subjectType: "subject_type",
      clientCredentialsScopes: "client_credentials_scopes",
      userId: "user_id",
      createdAt: "created_at",
      updatedAt: "updated_at",
      softwareId: "software_id",
      softwareVersion: "software_version",
      softwareStatement: "software_statement",
      redirectUris: "redirect_uris",
      postLogoutRedirectUris: "post_logout_redirect_uris",
      backchannelLogoutUri: "backchannel_logout_uri",
      backchannelLogoutSessionRequired: "backchannel_logout_session_required",
      tokenEndpointAuthMethod: "token_endpoint_auth_method",
      applicationType: "application_type",
      jwksUri: "jwks_uri",
      grantTypes: "grant_types",
      responseTypes: "response_types",
      requirePKCE: "require_pkce",
      dpopBoundAccessTokens: "dpop_bound_access_tokens",
      referenceId: "reference_id",
    },
  },
  oauthResource: {
    modelName: "oauth_resources",
    fields: {
      accessTokenTtl: "access_token_ttl",
      refreshTokenTtl: "refresh_token_ttl",
      signingAlgorithm: "signing_algorithm",
      signingKeyId: "signing_key_id",
      allowedScopes: "allowed_scopes",
      customClaims: "custom_claims",
      dpopBoundAccessTokensRequired: "dpop_bound_access_tokens_required",
      createdAt: "created_at",
      updatedAt: "updated_at",
      policyVersion: "policy_version",
    },
  },
  oauthClientResource: {
    modelName: "oauth_client_resources",
    fields: { clientId: "client_id", resourceId: "resource_id", createdAt: "created_at" },
  },
  oauthRefreshToken: {
    modelName: "oauth_refresh_tokens",
    fields: {
      clientId: "client_id",
      sessionId: "session_id",
      userId: "user_id",
      referenceId: "reference_id",
      authorizationCodeId: "authorization_code_id",
      requestedUserInfoClaims: "requested_user_info_claims",
      expiresAt: "expires_at",
      createdAt: "created_at",
      rotatedAt: "rotated_at",
      rotationReplayResponse: "rotation_replay_response",
      rotationReplayExpiresAt: "rotation_replay_expires_at",
      authTime: "auth_time",
    },
  },
  oauthAccessToken: {
    modelName: "oauth_access_tokens",
    fields: {
      clientId: "client_id",
      sessionId: "session_id",
      userId: "user_id",
      referenceId: "reference_id",
      authorizationCodeId: "authorization_code_id",
      requestedUserInfoClaims: "requested_user_info_claims",
      refreshId: "refresh_id",
      expiresAt: "expires_at",
      createdAt: "created_at",
    },
  },
  oauthConsent: {
    modelName: "oauth_consents",
    fields: {
      clientId: "client_id",
      userId: "user_id",
      referenceId: "reference_id",
      requestedUserInfoClaims: "requested_user_info_claims",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  oauthClientAssertion: {
    modelName: "oauth_client_assertions",
    fields: { expiresAt: "expires_at" },
  },
};

export const authServer = betterAuth({
  secret: process.env.BETTER_AUTH_SECRET,
  baseURL: process.env.BETTER_AUTH_URL,
  trustedOrigins: extraOrigins,
  database: pool,
  advanced: {
    database: { generateId: "uuid" },
  },
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    // Off so an admin creating an account isn't signed in as it; the
    // bootstrap sign-up (app/signup/actions.ts) signs in explicitly.
    autoSignIn: false,
    // Passwords from before Better Auth are bcrypt (cost 12), moved into
    // accounts.password by the migration; keep bcrypt for new ones too so
    // there is a single hash format.
    password: {
      hash: (password) => bcrypt.hash(password, 12),
      verify: ({ hash, password }) => bcrypt.compare(password, hash),
    },
  },
  user: {
    modelName: "users",
    fields: {
      emailVerified: "email_verified",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  session: {
    modelName: "sessions",
    fields: {
      userId: "user_id",
      expiresAt: "expires_at",
      ipAddress: "ip_address",
      userAgent: "user_agent",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  account: {
    modelName: "accounts",
    fields: {
      userId: "user_id",
      accountId: "account_id",
      providerId: "provider_id",
      accessToken: "access_token",
      refreshToken: "refresh_token",
      idToken: "id_token",
      accessTokenExpiresAt: "access_token_expires_at",
      refreshTokenExpiresAt: "refresh_token_expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  verification: {
    modelName: "verifications",
    fields: {
      expiresAt: "expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  hooks: {
    before: createAuthMiddleware(async (ctx) => {
      if (ctx.path === "/sign-up/email") await assertCanCreateUser();
    }),
  },
  databaseHooks: {
    user: {
      create: {
        before: async () => {
          await assertCanCreateUser();
        },
        // The oldest user is the bootstrap admin. Two sign-ups racing on a
        // fresh install can both pass the check above; only the first
        // becomes admin, the other stays a member.
        after: async (user) => {
          await pool.query(
            `UPDATE users SET role = 'admin'
              WHERE id = $1 AND id = (SELECT id FROM users ORDER BY created_at, id LIMIT 1)`,
            [user.id],
          );
        },
      },
    },
    session: {
      create: {
        // A disabled account can't sign in (its sessions were deleted when
        // it was disabled).
        before: async (session) => {
          const { rows } = await pool.query<{ disabled: boolean }>(
            `SELECT disabled_at IS NOT NULL AS disabled FROM users WHERE id = $1`,
            [session.userId],
          );
          if (rows[0]?.disabled) {
            throw new APIError("FORBIDDEN", {
              code: "ACCOUNT_DISABLED",
              message: "This account is disabled.",
            });
          }
        },
      },
    },
  },
  plugins: [
    username({
      schema: {
        user: { fields: { displayUsername: "display_username" } },
      },
    }),
    jwt({ schema: jwtSchema }),
    mcp({
      loginPage: "/login",
      consentPage: "/oauth/consent",
      resource: mcpResourceUrl(),
      scopes: [...MCP_SCOPES],
      schema: oauthProviderSchema,
    }),
    cimd({ fetchClientMetadataResource, metadataProfile: "mcp-2026-07-28" }),
    // Must stay last: it sets cookies from server actions (sign-in, sign-up).
    nextCookies(),
  ],
});

// Better Auth initializes its plugins as soon as this module loads, and
// mcp() writes its resource row (oauth_resources) then. Report a failure
// (no database, e.g. in unit tests that import a page) instead of leaving
// the rejection unhandled; requests that need auth still get the error.
authServer.$context.catch((err: unknown) => {
  console.error("auth: Better Auth failed to initialize", err);
});

// The current session ({ user, session }) or null, for server components,
// server actions and route handlers: `(await auth())?.user.id`.
export async function auth() {
  return authServer.api.getSession({ headers: await headers() });
}
