package sbom

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/pippinmole/upkeep.sh/server/internal/purl"
)

// SPDX 2.x JSON. Conventions seen in registry attestations (checked
// 2026-09-28 against postgres:17 and postgres:17-alpine, generated by
// "Tool: docker-scout-1.18.1", and moby/buildkit, by "Tool: syft-v1.51.0"):
//
//   - Every package's purl is an externalRef of type "purl".
//   - Docker Scout writes no arch and no upstream qualifier on deb purls.
//     The source package is a relationship instead: the binary is
//     GENERATED_FROM a package entry for its source (libc6 -> glibc).
//     We turn that into the purl's upstream qualifier, so the binary
//     interns with its real source like a host's dpkg entry does. Source
//     entries that aren't also an installed binary (glibc, gcc-14) are
//     dropped: their dpkg evidence names only other packages. They are
//     still covered through the binaries built from them.
//   - Docker Scout scopes distro purls with os_name / os_version /
//     os_distro qualifiers; Syft with distro=<id>-<version>. Neither
//     wrote an OPERATING-SYSTEM package, but newer generators may, and
//     it wins when present.
//   - Where a package was found: Scout relates it to files with
//     relationshipType OTHER and a comment "evident-by: …"; Syft says it
//     in sourceInfo ("acquired package info from APK DB:
//     /lib/apk/db/installed").

type spdxDoc struct {
	SPDXVersion  string `json:"spdxVersion"`
	CreationInfo struct {
		Creators []string `json:"creators"`
		Created  string   `json:"created"`
	} `json:"creationInfo"`
	Packages []struct {
		SPDXID                string `json:"SPDXID"`
		Name                  string `json:"name"`
		VersionInfo           string `json:"versionInfo"`
		PrimaryPackagePurpose string `json:"primaryPackagePurpose"`
		SourceInfo            string `json:"sourceInfo"`
		ExternalRefs          []struct {
			ReferenceType    string `json:"referenceType"`
			ReferenceLocator string `json:"referenceLocator"`
		} `json:"externalRefs"`
	} `json:"packages"`
	Files []struct {
		SPDXID   string `json:"SPDXID"`
		FileName string `json:"fileName"`
	} `json:"files"`
	Relationships []struct {
		Element string `json:"spdxElementId"`
		Related string `json:"relatedSpdxElement"`
		Type    string `json:"relationshipType"`
		Comment string `json:"comment"`
	} `json:"relationships"`
}

func parseSPDX(b []byte) (*Document, error) {
	var d spdxDoc
	if err := json.Unmarshal(b, &d); err != nil {
		return nil, fmt.Errorf("sbom: spdx: %w", err)
	}
	if !strings.HasPrefix(d.SPDXVersion, "SPDX-2.") {
		return nil, fmt.Errorf("sbom: spdx: unsupported version %q", d.SPDXVersion)
	}
	doc := &Document{Format: FormatSPDX, Created: parseTime(d.CreationInfo.Created)}
	var tools [][2]string
	for _, c := range d.CreationInfo.Creators {
		if t, ok := strings.CutPrefix(c, "Tool:"); ok {
			n, v := splitTool(t)
			tools = append(tools, [2]string{n, v})
		}
	}
	doc.ToolName, doc.ToolVersion = pickTool(tools)

	files := make(map[string]string, len(d.Files))
	for _, f := range d.Files {
		files[f.SPDXID] = f.FileName
	}
	generatedFrom := map[string]string{} // binary id -> source id
	isSource := map[string]bool{}
	evidence := map[string][]string{} // package id -> file names
	for _, r := range d.Relationships {
		switch {
		case r.Type == "GENERATED_FROM":
			generatedFrom[r.Element] = r.Related
			isSource[r.Related] = true
		case r.Type == "OTHER" && strings.HasPrefix(r.Comment, "evident-by"):
			if f, ok := files[r.Related]; ok {
				evidence[r.Element] = append(evidence[r.Element], f)
			}
		}
	}

	purls := make(map[string]purl.PURL, len(d.Packages))
	for _, p := range d.Packages {
		for _, ref := range p.ExternalRefs {
			if ref.ReferenceType != "purl" {
				continue
			}
			if u, err := purl.Parse(ref.ReferenceLocator); err == nil {
				purls[p.SPDXID] = u
				break
			}
		}
	}

	for _, p := range d.Packages {
		if p.PrimaryPackagePurpose == "OPERATING-SYSTEM" {
			doc.OS = purl.OSRelease{ID: strings.ToLower(p.Name), VersionID: p.VersionInfo}
			continue
		}
		u, ok := purls[p.SPDXID]
		if !ok {
			if p.VersionInfo != "" { // the document root has neither
				doc.Skipped++
			}
			continue
		}
		if isSource[p.SPDXID] && u.Type == "deb" && debSourceOnly(u.Name, evidence[p.SPDXID]) {
			continue
		}
		if src, ok := purls[generatedFrom[p.SPDXID]]; ok && src.Type == u.Type && u.Qualifier("upstream") == "" {
			q := make(map[string]string, len(u.Qualifiers)+1)
			for k, v := range u.Qualifiers {
				q[k] = v
			}
			q["upstream"] = src.Name + "@" + src.Version
			u.Qualifiers = q
		}
		paths := append(sourceInfoPaths(p.SourceInfo), evidence[p.SPDXID]...)
		doc.Packages = append(doc.Packages, Package{PURL: u, Paths: cleanPaths(u.Type, paths)})
	}
	if doc.OS.ID == "" {
		doc.OS = osFromPURLs(doc.Packages)
	}
	return doc, nil
}

// debSourceOnly reports whether a deb entry that other entries are
// GENERATED_FROM is only a source package: it has dpkg evidence, and none
// of it is the entry's own (var/lib/dpkg/info/<name>.list,
// <name>:<arch>.md5sums, …). Every installed deb has its own info files.
func debSourceOnly(name string, evidence []string) bool {
	own, info := false, false
	for _, f := range evidence {
		rest, ok := strings.CutPrefix(strings.TrimPrefix(f, "/"), "var/lib/dpkg/info/")
		if !ok {
			continue
		}
		info = true
		if i := strings.IndexAny(rest, ".:"); i >= 0 {
			rest = rest[:i]
		}
		if rest == name {
			own = true
		}
	}
	return info && !own
}

// sourceInfoPaths reads Syft's "acquired package info from <what>: <path>,
// <path>".
func sourceInfoPaths(s string) []string {
	rest, ok := strings.CutPrefix(s, "acquired package info from ")
	if !ok {
		return nil
	}
	i := strings.LastIndex(rest, ": ")
	if i < 0 {
		return nil
	}
	var out []string
	for _, p := range strings.Split(rest[i+2:], ",") {
		if p = strings.TrimSpace(p); strings.HasPrefix(p, "/") {
			out = append(out, p)
		}
	}
	return out
}
