-- Better Auth (docs/decisions/auth-self-hosted.md): database sessions and
-- username + password sign-in, replacing Auth.js JWT sessions.
--
-- Better Auth's `user` model maps onto the existing users table (web/src/lib/
-- auth.ts: user.modelName + snake_case field mapping), so every users(id)
-- foreign key stays as it is. Ids stay uuid, generated by Postgres
-- (advanced.database.generateId = "uuid").
--
-- The password moves from users.password_hash to a 'credential' row in
-- accounts (Better Auth's email/password provider). Existing hashes are
-- bcrypt and stay valid: auth.ts hashes and verifies with bcrypt.
--
-- Ownership: users (auth columns), sessions, accounts and verifications are
-- written only by Next.js (Better Auth). The Go server only reads users.id.

BEGIN;

-- name is required by Better Auth, which always writes it; the default only
-- serves rows inserted outside it (the Go integration tests).
-- username is optional in the username plugin (email sign-up may omit it),
-- hence nullable; Postgres UNIQUE allows many NULLs.
ALTER TABLE users
    ADD COLUMN name             text        NOT NULL DEFAULT '',
    ADD COLUMN email_verified   boolean     NOT NULL DEFAULT false,
    ADD COLUMN image            text,
    ADD COLUMN updated_at       timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN username         text        UNIQUE,
    ADD COLUMN display_username text;

-- Better Auth looks emails up lowercased. Auth.js sign-up already stored
-- them that way; this only catches rows written by hand.
UPDATE users SET email = lower(email) WHERE email <> lower(email);

-- Backfill username from the email local part: lowercased, reduced to the
-- username plugin's allowed characters ([a-z0-9_.]), 3..30 long, and made
-- unique with a numeric suffix (oldest account keeps the bare name).
DO $$
DECLARE
    u         record;
    base      text;
    candidate text;
    n         int;
BEGIN
    FOR u IN SELECT id, email FROM users ORDER BY created_at, id LOOP
        base := regexp_replace(lower(split_part(u.email, '@', 1)), '[^a-z0-9_.]', '', 'g');
        IF base = '' THEN
            base := 'user';
        END IF;
        IF length(base) < 3 THEN
            base := rpad(base, 3, '_'); -- rpad would also truncate longer ones
        END IF;
        base := left(base, 30);
        candidate := base;
        n := 1;
        WHILE EXISTS (SELECT 1 FROM users WHERE username = candidate) LOOP
            n := n + 1;
            candidate := left(base, 30 - length(n::text)) || n::text;
        END LOOP;
        UPDATE users
           SET username = candidate, display_username = candidate, name = candidate
         WHERE id = u.id;
    END LOOP;
END $$;

-- Better Auth session table: one row per signed-in browser; the cookie
-- carries token.
CREATE TABLE sessions (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       text NOT NULL UNIQUE,
    expires_at  timestamptz NOT NULL,
    ip_address  text,
    user_agent  text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);

-- Better Auth account table: one row per sign-in method. Password sign-in
-- is provider_id 'credential' with account_id = the user's id.
CREATE TABLE accounts (
    id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id               text NOT NULL,
    provider_id              text NOT NULL,
    access_token             text,
    refresh_token            text,
    id_token                 text,
    access_token_expires_at  timestamptz,
    refresh_token_expires_at timestamptz,
    scope                    text,
    password                 text,
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_id, account_id)
);
CREATE INDEX accounts_user_id_idx ON accounts (user_id);

-- Better Auth verification table: short-lived tokens (email verification,
-- password reset) should those features be turned on.
CREATE TABLE verifications (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    identifier  text NOT NULL,
    value       text NOT NULL,
    expires_at  timestamptz NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX verifications_identifier_idx ON verifications (identifier);

INSERT INTO accounts (user_id, account_id, provider_id, password, created_at, updated_at)
SELECT id, id::text, 'credential', password_hash, created_at, now()
  FROM users;

ALTER TABLE users DROP COLUMN password_hash;

COMMIT;
