-- MCP API tokens (docs/MCP.md#api-tokens-headless-agents,
-- docs/decisions/mcp-auth.md): bearer tokens (upk_...) for headless MCP
-- clients such as `claude -p` in cron or CI, stored by Better Auth's
-- @better-auth/api-key plugin.
--
-- api_tokens is the plugin's `apikey` model at 1.7.7. Columns and types
-- follow Better Auth's schema generator for Postgres, as in 0026: strings are
-- text, numbers integer, dates timestamptz, required fields NOT NULL, the id
-- a uuid generated by Postgres (advanced.database.generateId = "uuid").
-- permissions and metadata stay text: the plugin writes them as JSON strings
-- and parses them itself. Defaults the plugin fills in itself are repeated
-- here only for rows written outside it.
--
-- One change from the generator: referenceId (the owner; this install only
-- issues user tokens, never organization ones) is user_id, a uuid foreign key
-- to users, so a removed user's tokens go with them.
--
-- web/src/lib/auth.ts maps the model and fields onto these names (the
-- plugin's `schema` option); a field not listed keeps its name (e.g. name,
-- start, prefix, key, enabled, remaining, permissions, metadata):
--
--   apikey -> api_tokens
--     configId -> config_id, referenceId -> user_id,
--     refillInterval -> refill_interval, refillAmount -> refill_amount,
--     lastRefillAt -> last_refill_at, rateLimitEnabled -> rate_limit_enabled,
--     rateLimitTimeWindow -> rate_limit_time_window,
--     rateLimitMax -> rate_limit_max, requestCount -> request_count,
--     lastRequest -> last_request, expiresAt -> expires_at,
--     createdAt -> created_at, updatedAt -> updated_at
--
-- key holds the plugin's SHA-256 hash of the token (base64url), never the
-- token itself; start is its first characters (upk_ plus 8) for the list.
-- last_request is when the token last authenticated a call to /api/mcp. The
-- per-key rate limit columns are unused: the plugin's limiter is off and
-- /api/mcp limits every credential itself (lib/mcp/rate-limit.ts).
--
-- mcp_calls.api_token_id (0026) gets its foreign key: like oauth_client_id,
-- revoking a token keeps its call history and clears the reference.
--
-- Ownership: api_tokens is written only by Next.js (Better Auth's API key
-- plugin, and the Revoke action in Settings -> Integrations -> API tokens).

BEGIN;

CREATE TABLE api_tokens (
    id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    config_id              text NOT NULL DEFAULT 'default',
    name                   text,
    start                  text,
    user_id                uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    prefix                 text,
    key                    text NOT NULL UNIQUE,
    refill_interval        integer,
    refill_amount          integer,
    last_refill_at         timestamptz,
    enabled                boolean DEFAULT true,
    rate_limit_enabled     boolean DEFAULT true,
    rate_limit_time_window integer,
    rate_limit_max         integer,
    request_count          integer DEFAULT 0,
    remaining              integer,
    last_request           timestamptz,
    expires_at             timestamptz,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    permissions            text,
    metadata               text
);
CREATE INDEX api_tokens_config_id_idx ON api_tokens (config_id);
CREATE INDEX api_tokens_user_id_idx ON api_tokens (user_id);

ALTER TABLE mcp_calls
    ADD CONSTRAINT mcp_calls_api_token_id_fkey
    FOREIGN KEY (api_token_id) REFERENCES api_tokens(id) ON DELETE SET NULL;

COMMIT;
